---
- hosts: core
  become: true
  gather_facts: false

  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Remove swap file
      file:
        path: /swap.img
        state: absent

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

#    - name: Reboot
#      reboot:
#        reboot_timeout: 60