---
- hosts: core
  become: true
  gather_facts: false

  tasks:
    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Create containerd config directory
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config
      ansible.builtin.shell: containerd config default | tee /etc/containerd/config.toml
      changed_when: true

    - name: Fix pause image version
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: "sandbox = 'registry.k8s.io/pause:3.10.1'"
        replace: "sandbox = 'registry.k8s.io/pause:3.10'"

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted

    - name: Enable containerd
      ansible.builtin.service:
        name: containerd
        enabled: yes