[core]
core1 ansible_host=192.168.0.114  new_hostname=core
#core2 ansible_host=192.168.0.111  new_hostname=core-256

[core:vars]
ansible_user=user
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_extra_args='-o ConnectTimeout=5 -o ConnectionAttempts=1'
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3


