---
- hosts: core
  become: false
  gather_facts: false
  vars:
    ansible_ssh_extra_args: '-o ConnectTimeout=5 -o ConnectionAttempts=1 -t'
  vars_files:
    - "../group_vars/core/vault.yml"
  #serial: 1

  tasks:
    - name: Remove sudo-rs
      ansible.builtin.shell: echo "{{ sudo_pass }}" | sudo-rs -S apt-get remove -y sudo-rs
      register: result
      failed_when: false
      no_log: true

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ 'sudo-rs removed' if result.changed else 'sudo-rs was not installed' }}"