[core]
kube-control1 ansible_host=192.168.0.10  new_hostname=kube-control1
#kube-control2 ansible_host=192.168.0.116  new_hostname=kube-control2

[core:vars]
ansible_user=user
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_extra_args='-o ConnectTimeout=5 -o ConnectionAttempts=1'
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3


