#[ips] for only first step: pb_set_static_ip.yml
#   ansible_host  = dynamical ip from dhcp
#   set_static_ip = new static ip

#[core] for all next steps
#   ansible_host  = new static ip( from first step )

[ips]
kube-worker1 ansible_host=192.168.0.105  set_static_ip=192.168.0.21
kube-worker2 ansible_host=192.168.0.106  set_static_ip=192.168.0.22


[core]
kube-worker1 ansible_host=192.168.0.21  new_hostname=kube-worker1
kube-worker2 ansible_host=192.168.0.22  new_hostname=kube-worker2

[core:vars]
ansible_user=user
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_extra_args='-o ConnectTimeout=5 -o ConnectionAttempts=1'
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3


