---
- hosts: core
  become: true
  gather_facts: false
  tasks:

    - name: Rotate journal logs
      command: journalctl --rotate

    - name: Vacuum journal logs (keep last 1s)
      command: journalctl --vacuum-time=1s

    - name: Clear machine-id
      command: truncate -s 0 /etc/machine-id

    - name: Remove dbus machine-id
      file:
        path: /var/lib/dbus/machine-id
        state: absent

    - name: Remove SSH host keys
      shell: rm -f /etc/ssh/ssh_host_*