- name: Join worker to Kubernetes cluster
  hosts: core
  become: true
  gather_facts: false

  tasks:

    - name: Check if node already joined
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: kubeadm join
      ansible.builtin.command: >
        kubeadm join 192.168.0.10:6443
        --token 63xzj9.*****************
        --discovery-token-ca-cert-hash sha256:7d1eb************
      when: not kubelet_conf.stat.exists
      register: join_result

    - name: Show output
      ansible.builtin.debug:
        var: join_result.stdout_lines
      when: join_result.changed