---
- hosts: core
  become: true
  gather_facts: false

  tasks:
    - name: Setup machine-id
      command: systemd-machine-id-setup

    - name: Generate SSH host keys
      command: ssh-keygen -A

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    - name: Rotate journal logs
      command: journalctl --rotate

    - name: Vacuum journal logs
      command: journalctl --vacuum-time=1s