---
- hosts: core
  become: false
  gather_facts: false

  tasks:
    - name: Ping 8.8.8.8
      command: ping -c 3 8.8.8.8
      register: result
      changed_when: false

    - name: Show result
      debug:
        msg: "{{ result.stdout }}"